
### Get all Task

GET http://localhost:3000/tasks


### Create a Task

POST http://localhost:3000/tasks
Content-Type: application/json

{
    "name": "Create web site",
    "description": "Using React"
}


### Get a Task

GET http://localhost:3000/tasks/f664f305-0aff-4621-bf43-2ad17f5e1e4b

### Delete a Task
 
DELETE http://localhost:3000/tasks/270f0b2d-d5a8-4576-9ca7-66593bbda8c7


### Update a Task

PUT http://localhost:3000/tasks/f664f305-0aff-4621-bf43-2ad17f5e1e4b
Content-Type: application/json

{
    "name": "Create my web site",
    "description": "Using React"
}

### Count Tasks

GET http://localhost:3000/tasks/count


### Count Tasks in 'curl'

curl -X 'GET' \
  'http://localhost:3000/tasks/count' \
  -H 'accept: text/plain'
